CREATE TABLE CLASE(
	NUMERO_CLASE INTEGER NOT NULL,
	NOMBRE_CLASE VARCHAR(30),
	PRIMARY KEY (NUMERO_CLASE)
);

CREATE TABLE MAESTRO(
	NUMERO_MAESTRO INTEGER NOT NULL,
	NOMBRE_MAESTRO VARCHAR(100),
	PRIMARY KEY (NUMERO_MAESTRO)
);

CREATE TABLE ESTUDIANTE(
	ID INTEGER NOT NULL,
	NOMBRE VARCHAR(50),
	APELLIDO VARCHAR(50),
	CLASE INTEGER,
	PROFESOR INTEGER,
	PRIMARY KEY (ID),
	FOREIGN KEY (CLASE) REFERENCES CLASE(NUMERO_CLASE),
	FOREIGN KEY (PROFESOR) REFERENCES MAESTRO(NUMERO_MAESTRO)
);

